
//let arr = ["\"one\"", "\"two\"", "\"three\"", "\"four\"", "\"five\"", "\"six\"", "\"seven\"", "\"eight\"", "\"nine\"", "\"ten\""];

let arr = ["\"Why don't scientists trust atoms? Because they make up everything!\"",
    "\"What did the grape say when it got stepped on? Nothing, it just let out a little wine.\"",
    "\"Why don't skeletons fight each other? They don't have the guts.\"",
    "\"What did one wall say to the other wall? I'll meet you at the corner!\"",
    "\"Why don't eggs tell jokes? Because they might crack up!\"",
    "\"Why did the bicycle fall over? It was two-tired!\"",
    "\"How do you organize a space party? You planet!\"",
    "\"Why did the scarecrow win an award? Because he was outstanding in his field!\"",
    "\"Why did the tomato turn red? Because it saw the salad dressing!\"",
    "\"Why don't oysters donate to charity? Because they are shellfish!\"",
    "\"How does a penguin build its house? Igloos it together!\"",
    "\"What do you call a bear with no teeth? A gummy bear!\"",
    "\"Why did the golfer bring two pairs of pants? In case he got a hole in one!\"",
    "\"How do you catch a squirrel? Climb a tree and act like a nut!\"",
    "\"What do you get when you cross a snowman and a vampire? Frostbite!\"",
    "\"Why did the math book look sad? Because it had too many problems!\"",
    "\"Why don't skeletons fight each other? They don't have the guts!\"",
    "\"What do you call a fish wearing a crown? King mackerel!\"",
    "\"How do you make a tissue dance? You put a little boogie in it!\"",
    "\"Why don't scientists trust atoms? Because they make up everything!\"",
    "\"Why couldn't the bicycle stand up by itself? It was two-tired!\"",
    "\"What do you call fake spaghetti? An impasta!\"",
    "\"What did one hat say to the other hat? You stay here, I'll go on ahead!\"",
    "\"Why did the tomato turn red? Because it saw the salad dressing!\"",
    "\"What did one wall say to the other wall? I'll meet you at the corner!\"",
    "\"How do you organize a space party? You planet!\"",
    "\"Why did the scarecrow win an award? Because he was outstanding in his field\"",
    "\"How do you catch a squirrel? Climb a tree and act like a nut!\"",
    "\"Why don't eggs tell jokes? Because they might crack up!\"",
    "\"What did one snowman say to the other snowman? Do you smell carrots?\"",
    "\"Why don't skeletons fight each other? They don't have the guts!\"",
    "\"What do you call a bear with no teeth? A gummy bear!\"",
    "\"How does a penguin build its house? Igloos it together!\"",
    "\"What do you get when you cross a snowman and a vampire? Frostbite!\"",
    "\"Why did the math book look sad? Because it had too many problems!\"",
    "\"Why did the golfer bring two pairs of pants? In case he got a hole in one!\"",
    "\"What do you call a fish wearing a crown? King mackerel!\"",
    "\"How do you make a tissue dance? You put a little boogie in it!\"",
    "\"Why don't scientists trust atoms? Because they make up everything!\"",
    "\"Why couldn't the bicycle stand up by itself? It was two-tired!\"",
    "\"What do you call fake spaghetti? An impasta!\"",
    "\"Why did the tomato turn red? Because it saw the salad dressing!\"",
    "\"Why did the scarecrow win an award? Because he was outstanding in his field!\"",
    "\"How do you catch a squirrel? Climb a tree and act like a nut!\"",
    "\"Why don't eggs tell jokes? Because they might crack up!\"",
    "\"What did one snowman say to the other snowman? Do you smell carrots?\"",
    "\"Why don't skeletons fight each other? They don't have the guts!\"",
    "\"What do you call a bear with no teeth? A gummy bear!\"",
    "\"How does a penguin build its house? Igloos it together!\"",
    "\"What do you get when you cross a snowman and a vampire? Frostbite!\"",
    "\"Why did the math book look sad? Because it had too many problems!\"",
    "\"Why did the golfer bring two pairs of pants? In case he got a hole in one!\"",
    "\"What do you call a fish wearing a crown? King mackerel!\"",
    "\"How do you make a tissue dance? You put a little boogie in it!\"",
    "\"What do you call a fake noodle? An impasta!\"",
    "\"How do you organize a space party? You planet!\"",
    "\"Why don't scientists trust atoms? Because they make up everything!\"",
    "\"Why couldn't the bicycle find its way home? It lost its bearings\"",
    "\"What do you call a pig that knows karate? Pork chop!\"",
    "\"Why don't ants ever get sick? Because they have little anty-bodies!\"",
    "\"Why don't skeletons fight each other? They don't have the guts\"",
    "\"How does a cucumber become a pickle? It goes through a jarring experience!\"",
    "\"What did one hat say to the other hat? You stay here, I'll go on ahead!\"",
    "\"Why did the tomato turn red? Because it saw the salad dressing!\"",
    "\"How do you organize a space party? You planet!\"",
    "\"Why did the scarecrow win an award? Because he was outstanding in his field!\"",
    "\"How do you catch a squirrel? Climb a tree and act like a nut!\"",
    "\"What did one snowman say to the other snowman? Do you smell carrots?\"",
    "\"Why don't skeletons fight each other? They don't have the guts\"",
    "\"What do you call a bear with no teeth? A gummy bear\"",
    "\"How does a penguin build its house? Igloos it together\"",
    "\"What do you get when you cross a snowman and a vampire? Frostbite!\"",
    "\"Why did the math book look sad? Because it had too many problems\"",
    "\"Why did the golfer bring two pairs of pants? In case he got a hole in one!\"",
    "\"What do you call a fish wearing a crown? King mackerel!\"",
    "\"How do you make a tissue dance? You put a little boogie in it\"",
    "\"Why don't scientists trust atoms? Because they make up everything\"",
    "\"Why couldn't the bicycle stand up by itself? It was two-tired!\"",
    "\"What do you call fake spaghetti? An impasta\"",
    "\"Why did the tomato turn red? Because it saw the salad dressing!\"",
    "\"What did one wall say to the other wall? I'll meet you at the corner!\"",
    "\"How do you organize a space party? You planet\"",
    "\"Why did the scarecrow win an award? Because he was outstanding in his field!\"",
    "\"How do you catch a squirrel? Climb a tree and act like a nut!\"",
    "\"Why don't skeletons fight each other? They don't have the guts!\"",
    "\"What do you call a bear with no teeth? A gummy bear!\"",
    "\"How does a penguin build its house? Igloos it together!\"",
    "\"What do you get when you cross a snowman and a vampire? Frostbite!\"",
    "\"Why did the math book look sad? Because it had too many problems!\"",
    "\"Why did the golfer bring two pairs of pants? In case he got a hole in one!\"",
    "\"What do you call a fish wearing a crown? King mackerel!\"",
    "\"How do you make a tissue dance? You put a little boogie in it!\"",
    "\"What do you call a fake noodle? An impasta!\"",
    "\"Why don't scientists trust atoms? Because they make up everything!\"",
    "\"Why couldn't the bicycle find its way home? It lost its bearings!\"",
    "\"What do you call a pig that knows karate? Pork chop!\"",
    "\"I'm reading a book about anti-gravity. It's impossible to put down!\"",
    "\"Why did the math book look sad? Because it had too many problems!\"",
    "\"I used to be a baker, but I couldn't make enough dough.\"",
    "\"Why don't scientists trust atoms? Because they make up everything!\""
];
console.log(arr.length)


let a = (e) => {
    
    let r = Math.floor(Math.random() * 101);
    console.log(document.body.firstElementChild.lastElementChild.innerHTML = arr[r]);
}
setInterval(a, 3000)
//$0.innerHTML="JS";